name: Deploy AppSync Prod

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.13.1
      - run: yarn install
      - name: Run Test
        run: yarn test
        env:
          MONGODB_WORK_CONN: ${{ secrets.MONGODB_WORK_CONN }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.13.1
      - run: yarn install
      - name: Serverless Deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage dev
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
